version: '2'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/frontend
      - ./client:/client
      #issue with which node_modules folder docker sees (see https://github.com/barrysteyn/node-scrypt/issues/148)
      - ./client/visualizer/node_modules
      - ./client/playback/node_modules
      - ./schema:/schema
    ports:
      - 3000:3000
    # environment:
    #   - NODE_PATH=/install/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - 8000:80
    environment:
      - DJANGO_SETTINGS_MODULE=dev_settings_real
      - DB_HOST_BC_DEV=db
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate && uwsgi --ini uwsgi.ini'
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate && python manage.py runserver 0.0.0.0:80'

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=battlecode
      - POSTGRES_DB=battlecode
      - POSTGRES_PASSWORD=mysecretpassword
